# This is a basic workflow to help you get started with Actions

name: 自动打卡

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron:  '30 0,12 * * *'

jobs:
  bot:
    runs-on: windows-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools requests beautifulsoup4 lxml
      - name: 'sendDingding'
        run: python BaiduIndex.py
